# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - poc-walmart

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn -B package --file poc-walmart/pom.xml

      - name: Archive artifacts
        run: |
          mkdir -p ${{ github.workspace }}/artifacts
          cp -R poc-walmart/target/*.jar ${{ github.workspace }}/artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: drop
          path: ${{ github.workspace }}/artifacts

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: drop
          path: '${{ github.workspace }}/artifacts'

      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6119DC4A661942A1BE07DD271CCE7661 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_31C8EC1FC4674BCA94302735D6E5FDDF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_037165F9DEBE4DCD84F528305FDA4869 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'poc-walmart'
          slot-name: 'Production'
          package: ${{ github.workspace }}/artifacts/*.jar
        
          
